name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Install nokogiri build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            patch \
            ruby-dev \
            zlib1g-dev \
            liblzma-dev \
            libxml2-dev \
            libxslt1-dev \
            xz-utils

      - uses: RbMo7/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
